24hr_clock: false
accent_color: '#00ff00'
animated_transitions: true
auto_start_break: true
auto_start_work: false
auto_tags: true
auto_task_complete: true
blur_background: true
break_end_cmd: scripts\classical_music.ps1 -Action start -Volume 20
break_start_cmd: ''
classical_music: true
classical_music_default_playlist: C:\Users\ahm_e\mpv\PlayList\ClassicalMusic.m3u
classical_music_genres:
- baroque
- classical
- romantic
- modern
classical_music_local_mode: true
classical_music_online_playlists:
- https://www.youtube.com/watch?v=mdJU5ogrPMY
classical_music_playlist_dir: C:\Users\ahm_e\mpv\PlayList
classical_music_volume: 70
color_scheme: forest
compact_mode: false
custom_css: ''
custom_notifications: true
dark_theme: true
data_retention_days: 365
deep_focus_mode: false
desktop_notifications: true
detailed_analytics: true
distraction_tracking: true
export_format: csv
fade_music_transitions: true
fade_sound: true
goal_tracking: true
gradient_backgrounds: true
idle_cmd: ''
long_break_interval: 4
long_break_mins: 15
long_break_msg: Take a long break
max_daily_sessions: 0
min_work_time: 5
motivational_messages: true
mpv_executable: C:\Users\ahm_e\mpv\portable_config\mpv.exe
mpv_extra_args: --no-video --shuffle --loop-playlist
notification_persistence: 5
notification_priority: normal
notify: true
notify_early_warning: 2
notify_sound: true
pause_music_on_break: true
post_break_cmd: ''
pre_break_cmd: scripts\classical_music.ps1 -Action stop
productivity_scoring: true
productivity_trends: true
resume_incomplete: true
save_incomplete: true
session_cmd: scripts\classical_music.ps1 -Action start -Volume 30
session_goals: 8
session_quality_rating: true
short_break_mins: 5
short_break_msg: Take a breather
show_progress_bar: true
show_seconds: true
smart_break_adjustment: true
sound: ''
sound_on_break: false
sound_volume: 100
stats_default_view: week
task_file: ~/tasks.md
time_blocking: true
time_format: '15:04'
todo_integration: false
track_idle_time: true
transparency: 0.95
weekly_goals: 40
weekly_reports: true
work_end_cmd: scripts\classical_music.ps1 -Action stop
work_mins: 25
work_msg: Focus on your task
work_start_cmd: scripts\classical_music.ps1 -Action start -Volume 30
