# Session Timings
work_mins: 25
short_break_mins: 5
long_break_mins: 15
long_break_interval: 4

# Session Messages
work_msg: Focus on your task
short_break_msg: Take a breather
long_break_msg: Take a long break

# Notification Settings
notify: true
notify_sound: true # enable notification sounds
# notify_sound_work: "bell.mp3" # custom sound for work completion
# notify_sound_break: "chime.mp3" # custom sound for break completion
notify_early_warning: 2 # minutes before session end to show warning

# Session Behavior
auto_start_work: false
auto_start_break: true
resume_incomplete: true # resume incomplete sessions on startup
save_incomplete: true # save progress when interrupted
max_daily_sessions: 0 # 0 for unlimited
min_work_time: 5 # minimum minutes to count as completed session

# Time Display
24hr_clock: false
show_seconds: true # show seconds in timer
time_format: "15:04" # Go time format string
show_progress_bar: true # show visual progress bar

# Sound Settings
sound: ""
sound_volume: 70 # volume percentage
sound_on_break: false
fade_sound: true # fade in/out sound transitions

# Theme Settings
dark_theme: true
accent_color: "#00ff00" # custom highlight color
compact_mode: false # minimize UI elements

# Statistics
track_idle_time: true # track system idle time
auto_tags: true # automatically tag sessions based on active window
stats_default_view: "week" # default statistics view (day/week/month)
export_format: "csv" # default export format for statistics

# Custom Commands
session_cmd: ""
pre_break_cmd: "" # execute before break starts
post_break_cmd: "" # execute after break ends
idle_cmd: "" # execute when system becomes idle

# Task Management
todo_integration: false # enable todo list integration
task_file: "~/tasks.md" # path to task file
auto_task_complete: true # mark tasks complete after sessions
